directories:
  "/":
    IrresponsibleModule:
      enabled: false

    FeatureEnvy:
      enabled: false

    NilCheck:
      enabled: false

    TooManyStatements:
      enabled: true
      max_statements: 10

    UtilityFunction:
      enabled: true
      public_methods_only: true

# Directories and files below will not be scanned at all
exclude_paths:
  - bin
  - config
  - db
  - log
  - public
  - spec
  - storage
  - tmp
  - vendor
