version: '3'

services:

  sportsball-db:
    image: postgres:11
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: 
      - .env.local
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  sportsball-web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/sportsball
      - bundle-path:/bundle
    env_file: 
      - .env.local
    environment:
      - BUNDLE_PATH=/bundle/vendor
    ports:
      - "3003:3000"
    depends_on:
      - sportsball-db
  
volumes:
  postgres-data:
  bundle-path:
